#!/usr/bin/env bash
# Bolo one-command installer: clone the repo, run this, dictate.
#   git clone <repo> && cd Bolo && ./install.sh
# Idempotent — safe to re-run after `git pull` to update.
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
BIN_DIR="$HOME/.local/bin"
CONF_DIR="$HOME/.config/bolo"

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*"; exit 1; }

[ "$(uname -s)" = "Linux" ] || die "Bolo currently supports Linux (GNOME/Wayland). macOS support is planned — the audio/transcription core is portable, but text injection and hotkeys need a macOS backend."

# ---------------------------------------------------------------- rust
if ! command -v cargo >/dev/null 2>&1 && [ ! -x "$HOME/.cargo/bin/cargo" ]; then
    say "Installing Rust via rustup (one-time)…"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
fi
export PATH="$HOME/.cargo/bin:$PATH"

# ------------------------------------------------------- build/runtime deps
# Needs: C toolchain + cmake (whisper.cpp), ALSA headers (cpal),
# libclang (bindgen), wl-clipboard + xclip (paste), pulseaudio utils (chimes).
need_pkgs=()
command -v cc >/dev/null 2>&1 || need_pkgs+=(build-essential)
command -v cmake >/dev/null 2>&1 || need_pkgs+=(cmake)
command -v pkg-config >/dev/null 2>&1 || need_pkgs+=(pkg-config)
pkg-config --exists alsa 2>/dev/null || need_pkgs+=(libasound2-dev)
ls /usr/lib/llvm-*/lib/libclang*.so* >/dev/null 2>&1 \
    || ls /usr/lib/x86_64-linux-gnu/libclang*.so* >/dev/null 2>&1 \
    || [ -n "${LIBCLANG_PATH:-}" ] || need_pkgs+=(libclang-dev)
command -v wl-copy >/dev/null 2>&1 || need_pkgs+=(wl-clipboard)
command -v xclip >/dev/null 2>&1 || need_pkgs+=(xclip)
command -v paplay >/dev/null 2>&1 || need_pkgs+=(pulseaudio-utils)

local_dev_shim() {
    # No sudo: extract the dev packages locally and point cargo at them.
    say "No sudo — extracting ALSA/libclang locally under ~/.local (no root needed)…"
    local tmp; tmp="$(mktemp -d)"
    ( cd "$tmp" && apt-get download libasound2-dev libclang1-14 libclang-common-14-dev )
    mkdir -p "$HOME/.local/alsa-dev" "$HOME/.local/clang-dev"
    for deb in "$tmp"/libasound2-dev_*.deb; do dpkg -x "$deb" "$HOME/.local/alsa-dev"; done
    for deb in "$tmp"/libclang*_*.deb; do dpkg -x "$deb" "$HOME/.local/clang-dev"; done
    local pcdir="$HOME/.local/alsa-dev/usr/lib/x86_64-linux-gnu/pkgconfig"
    sed -i "s|^prefix=.*|prefix=$HOME/.local/alsa-dev/usr|" "$pcdir/alsa.pc"
    ln -sf /lib/x86_64-linux-gnu/libasound.so.2 \
        "$HOME/.local/alsa-dev/usr/lib/x86_64-linux-gnu/libasound.so"
    mkdir -p "$REPO/.cargo"
    cat > "$REPO/.cargo/config.toml" <<EOF
# Generated by install.sh: local dev-package shims (no sudo available).
[env]
PKG_CONFIG_PATH = "$pcdir"
LIBCLANG_PATH = "$HOME/.local/clang-dev/usr/lib/llvm-14/lib"
EOF
    rm -rf "$tmp"
}

if [ "${#need_pkgs[@]}" -gt 0 ]; then
    say "Missing system packages: ${need_pkgs[*]}"
    if sudo -n true 2>/dev/null || { [ -t 0 ] && sudo -v; }; then
        sudo apt-get install -y "${need_pkgs[@]}"
    else
        local_dev_shim
    fi
fi

# ---------------------------------------------------------------- build
say "Building Bolo (release)…"
( cd "$REPO" && cargo build --release )

# ---------------------------------------------------------------- install
mkdir -p "$BIN_DIR" "$CONF_DIR"
ln -sf "$REPO/target/release/bolo" "$BIN_DIR/bolo"
say "Linked $BIN_DIR/bolo"
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) warn "$BIN_DIR is not on your PATH — add:  export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac

if [ ! -f "$CONF_DIR/config.toml" ]; then
    cp "$REPO/config.toml" "$CONF_DIR/config.toml"
    say "Config created at $CONF_DIR/config.toml (edit anytime with: bolo settings)"
fi

# ---------------------------------------------------------------- groq key
if [ -z "${GROQ_API_KEY:-}" ] && ! grep -q '^GROQ_API_KEY=' "$HOME/.env" 2>/dev/null; then
    if [ -t 0 ]; then
        printf 'Groq API key (Enter to skip and use local-only transcription): '
        read -r key
        if [ -n "$key" ]; then
            printf 'GROQ_API_KEY=%s\n' "$key" >> "$HOME/.env"
            chmod 600 "$HOME/.env"
            say "Saved to ~/.env (never committed, never in config)"
        fi
    else
        warn "No GROQ_API_KEY found. For cloud transcription put it in ~/.env: GROQ_API_KEY=…"
    fi
fi

# ---------------------------------------------------------------- hotkeys
if command -v gsettings >/dev/null 2>&1 && [ "${XDG_CURRENT_DESKTOP:-}" != "${XDG_CURRENT_DESKTOP#*GNOME}" -o "${XDG_CURRENT_DESKTOP:-}" = "GNOME" ]; then
    say "Registering GNOME hotkeys (Ctrl+Space, Alt+P, Alt+I)…"
    "$REPO/scripts/install-hotkey.sh" || warn "hotkey registration failed — run scripts/install-hotkey.sh manually"
else
    warn "Non-GNOME desktop: bind these commands to hotkeys yourself: 'bolo toggle', 'bolo pause', 'bolo insert-last'"
fi

# ---------------------------------------------------------------- daemon service
if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
    mkdir -p "$HOME/.config/systemd/user"
    cp "$REPO/scripts/bolo.service" "$HOME/.config/systemd/user/bolo.service"
    systemctl --user daemon-reload
    "$BIN_DIR/bolo" quit >/dev/null 2>&1 || true   # stop any hand-started daemon
    systemctl --user enable --now bolo.service
    say "Daemon installed as a user service (starts on login):  systemctl --user status bolo"
else
    warn "systemd user session unavailable — start the daemon manually: bolo daemon &"
fi

# ---------------------------------------------------------------- local model
provider="$(grep -E '^provider *= *"' "$CONF_DIR/config.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')"
if [ "$provider" = "whisper" ]; then   # faster-whisper self-downloads via its sidecar
    model="$(grep -E '^model *= *"' "$CONF_DIR/config.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')"
    say "Local provider '$provider' selected — pre-fetching model '$model'…"
    "$BIN_DIR/bolo" model download "$model" || warn "model download failed; it will retry on first use"
fi

cat <<'EOF'

  Bolo is ready.
    Ctrl+Space  start dictating / finish (text pastes at your cursor)
    Alt+P       pause / resume (copy text while paused to splice it in)
    Alt+I       insert clipboard while paused · re-type last transcript when idle
    bolo settings   full settings UI in the terminal (engine, models, vocabulary…)

  First dictation shows a one-time GNOME permission dialog (portal) — accept it.
EOF
