#!/usr/bin/env bash
# Bolo one-command installer for macOS & Linux: clone the repo, run this, dictate.
#   git clone https://github.com/Mani212005/Bolo.git && cd Bolo && ./install.sh
# Idempotent — safe to re-run after `git pull` to update.
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
CONF_DIR="$HOME/.config/bolo"
OS="$(uname -s)"

# Determine preferred install binary directory
if [ -d "$HOME/.cargo/bin" ]; then
    BIN_DIR="$HOME/.cargo/bin"
else
    BIN_DIR="$HOME/.local/bin"
fi

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*"; exit 1; }

say "Detected OS: $OS ($(uname -m))"

# ---------------------------------------------------------------- rust toolchain
if ! command -v cargo >/dev/null 2>&1 && [ ! -x "$HOME/.cargo/bin/cargo" ]; then
    say "Installing Rust via rustup (one-time)…"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
fi
export PATH="$HOME/.cargo/bin:$BIN_DIR:$PATH"

# ------------------------------------------------------- platform dependencies
if [ "$OS" = "Linux" ]; then
    need_pkgs=()
    command -v cc >/dev/null 2>&1 || need_pkgs+=(build-essential)
    command -v cmake >/dev/null 2>&1 || need_pkgs+=(cmake)
    command -v pkg-config >/dev/null 2>&1 || need_pkgs+=(pkg-config)
    pkg-config --exists alsa 2>/dev/null || need_pkgs+=(libasound2-dev)
    ls /usr/lib/llvm-*/lib/libclang*.so* >/dev/null 2>&1 \
        || ls /usr/lib/x86_64-linux-gnu/libclang*.so* >/dev/null 2>&1 \
        || [ -n "${LIBCLANG_PATH:-}" ] || need_pkgs+=(libclang-dev)
    command -v wl-copy >/dev/null 2>&1 || need_pkgs+=(wl-clipboard)
    command -v xclip >/dev/null 2>&1 || need_pkgs+=(xclip)
    command -v paplay >/dev/null 2>&1 || need_pkgs+=(pulseaudio-utils)

    local_dev_shim() {
        say "No sudo — extracting ALSA/libclang locally under ~/.local (no root needed)…"
        local tmp; tmp="$(mktemp -d)"
        ( cd "$tmp" && apt-get download libasound2-dev libclang1-14 libclang-common-14-dev )
        mkdir -p "$HOME/.local/alsa-dev" "$HOME/.local/clang-dev"
        for deb in "$tmp"/libasound2-dev_*.deb; do dpkg -x "$deb" "$HOME/.local/alsa-dev"; done
        for deb in "$tmp"/libclang*_*.deb; do dpkg -x "$deb" "$HOME/.local/clang-dev"; done
        local pcdir="$HOME/.local/alsa-dev/usr/lib/x86_64-linux-gnu/pkgconfig"
        sed -i "s|^prefix=.*|prefix=$HOME/.local/alsa-dev/usr|" "$pcdir/alsa.pc"
        ln -sf /lib/x86_64-linux-gnu/libasound.so.2 \
            "$HOME/.local/alsa-dev/usr/lib/x86_64-linux-gnu/libasound.so"
        mkdir -p "$REPO/.cargo"
        cat > "$REPO/.cargo/config.toml" <<EOF
# Generated by install.sh: local dev-package shims (no sudo available).
[env]
PKG_CONFIG_PATH = "$pcdir"
LIBCLANG_PATH = "$HOME/.local/clang-dev/usr/lib/llvm-14/lib"
EOF
        rm -rf "$tmp"
    }

    if [ "${#need_pkgs[@]}" -gt 0 ]; then
        say "Missing Linux system packages: ${need_pkgs[*]}"
        if sudo -n true 2>/dev/null || { [ -t 0 ] && sudo -v; }; then
            sudo apt-get update -qq && sudo apt-get install -y "${need_pkgs[@]}"
        else
            local_dev_shim
        fi
    fi

elif [ "$OS" = "Darwin" ]; then
    if ! command -v swiftc >/dev/null 2>&1; then
        say "Installing macOS Command Line Tools (for swiftc)…"
        xcode-select --install || true
    fi
else
    die "Unsupported operating system: $OS. Bolo supports macOS and Linux."
fi

# ---------------------------------------------------------------- build
say "Building Bolo (release)…"
( cd "$REPO" && cargo build --release )

# Install to ~/.local/bin and ~/.cargo/bin
mkdir -p "$HOME/.local/bin" "$CONF_DIR"
cp "$REPO/target/release/bolo" "$HOME/.local/bin/bolo"
say "Installed $HOME/.local/bin/bolo"

if [ -d "$HOME/.cargo/bin" ]; then
    cp "$REPO/target/release/bolo" "$HOME/.cargo/bin/bolo"
    say "Installed $HOME/.cargo/bin/bolo"
fi

if [ "$OS" = "Darwin" ]; then
    say "Compiling native Cocoa popup app (bolo-ui)…"
    swiftc -O "$REPO/src/ui/BoloApp.swift" -o "$REPO/target/release/bolo-ui" -framework Cocoa -framework WebKit
    cp "$REPO/target/release/bolo-ui" "$HOME/.local/bin/bolo-ui"
    say "Installed $HOME/.local/bin/bolo-ui"
    if [ -d "$HOME/.cargo/bin" ]; then
        cp "$REPO/target/release/bolo-ui" "$HOME/.cargo/bin/bolo-ui"
        say "Installed $HOME/.cargo/bin/bolo-ui"
    fi
fi

# ---------------------------------------------------------------- config
if [ ! -f "$CONF_DIR/config.toml" ]; then
    cp "$REPO/config.toml" "$CONF_DIR/config.toml"
    say "Config created at $CONF_DIR/config.toml"
fi

# ---------------------------------------------------------------- groq key
if [ -z "${GROQ_API_KEY:-}" ] && ! grep -q '^GROQ_API_KEY=' "$HOME/.env" 2>/dev/null; then
    if [ -t 0 ]; then
        printf 'Groq API key (Enter to skip and use local-only transcription): '
        read -r key
        if [ -n "$key" ]; then
            printf 'GROQ_API_KEY=%s\n' "$key" >> "$HOME/.env"
            chmod 600 "$HOME/.env"
            say "Saved to ~/.env (never committed, never in config)"
        fi
    else
        warn "No GROQ_API_KEY found. For cloud transcription put it in ~/.env: GROQ_API_KEY=…"
    fi
fi

# ---------------------------------------------------------------- platform integration
if [ "$OS" = "Linux" ]; then
    # GNOME Hotkeys
    if command -v gsettings >/dev/null 2>&1 && [ "${XDG_CURRENT_DESKTOP:-}" != "${XDG_CURRENT_DESKTOP#*GNOME}" -o "${XDG_CURRENT_DESKTOP:-}" = "GNOME" ]; then
        say "Registering GNOME hotkeys (Ctrl+Space, Alt+P, Alt+I)…"
        "$REPO/scripts/install-hotkey.sh" || warn "hotkey registration failed — run scripts/install-hotkey.sh manually"
    fi

    # Systemd Service
    if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
        mkdir -p "$HOME/.config/systemd/user"
        cp "$REPO/scripts/bolo.service" "$HOME/.config/systemd/user/bolo.service"
        systemctl --user daemon-reload
        "$BIN_DIR/bolo" quit >/dev/null 2>&1 || true
        systemctl --user enable --now bolo.service
        say "Daemon installed as user service: systemctl --user status bolo"
    fi

    # App Entry
    mkdir -p "$HOME/.local/share/applications" "$HOME/.local/share/icons/hicolor/scalable/apps"
    cp "$REPO/assets/bolo.svg" "$HOME/.local/share/icons/hicolor/scalable/apps/bolo.svg" 2>/dev/null || true
    if [ -f "$REPO/scripts/bolo-settings.desktop" ]; then
        sed "s|^Exec=.*|Exec=$BIN_DIR/bolo settings|" "$REPO/scripts/bolo-settings.desktop" \
            > "$HOME/.local/share/applications/bolo-settings.desktop"
        command -v update-desktop-database >/dev/null 2>&1 \
            && update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true
    fi
fi

# ---------------------------------------------------------------- PATH check
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) warn "$BIN_DIR is not on your PATH — add to your shell profile:  export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

# ---------------------------------------------------------------- welcome
if [ "$OS" = "Darwin" ]; then
cat <<'EOF'

  🎙️ Bolo is installed and ready on macOS!

  Quickstart:
    bolo        Launch daemon & open native popup dashboard
    bolo exit   Stop daemon and close popup window

  Shortcuts:
    Ctrl+Space  Start dictating / finish (text pastes at cursor)
    Option+V    Quick-splice clipboard text into speech without pausing
    Option+P    Pause / resume recording
    Option+I    Re-type last transcription at cursor

  Permissions (macOS System Settings > Privacy & Security):
    • Microphone        Allow audio capture
    • Accessibility     Allow typing text at cursor (Cmd+V)
    • Input Monitoring  Allow global Ctrl+Space push-to-talk hotkey

EOF
else
cat <<'EOF'

  🎙️ Bolo is installed and ready on Linux!

  Quickstart:
    bolo        Launch daemon & open dashboard
    bolo exit   Stop daemon

  Shortcuts:
    Ctrl+Space  Start dictating / finish (text pastes at cursor)
    Alt+V       Quick-splice clipboard text into speech without pausing
    Alt+P       Pause / resume recording
    Alt+I       Insert clipboard while paused · re-type last transcript when idle

EOF
fi
